import numpy as np<br>
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]<br>
array_list = np.array(object = list_)<br>

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

Yes, there is a difference in the data type of the `list_` and `array_list` variables. The elements in the `list_` variable are strings, while the elements in the `array_list` variable are of the data type inferred by NumPy. Let's write a code to print the data types of both variables:

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)
```

This code prints the data type of the first element in the `list_` variable and the data type of the elements in the `array_list` variable. The data type of `list_[0]` will be `str` (string), and the data type of `array_list` will be inferred by NumPy based on the input elements, and it will typically be `numpy.str_` or `numpy.object_` in this case, depending on the NumPy version.

**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

Certainly! You can use a loop to iterate through each element in both the `list_` and `array_list` and print their respective data types. Here's the code:

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))
```

This code will print the data type of each element in both `list_` and `array_list`. Note that in the case of `array_list`, the data type may be the NumPy specific data type like `numpy.str_` or `numpy.object_`.

**Q3. Considering the following changes in the variable, array_list:**<br>
array_list = np.array(object = list_, dtype = int)<br>
Will there be any difference in the data type of the elements present in both the variables, list_ and<br>
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.<br>
Consider the below code to answer further questions:<br>
import numpy as np<br>
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]<br>
num_array = np.array(object = num_list)<br>

Yes, there will be a difference in the data type of the elements present in both the `list_` and the updated `array_list` because you've specified the `dtype` as `int` during the creation of `array_list`. Let's print the data types of each element in both variables:

```python
import numpy as np

# Original list
list_ = ['1', '2', '3', '4', '5']

# Updated array_list with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print data types of each element in updated array_list
print("\nData types in updated array_list:")
for element in array_list:
    print(type(element))
```

Now, regarding the provided code snippet:

```python
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
```

This creates a 2D NumPy array (`num_array`) from the nested list `num_list`. Each element in `num_array` will be of type `int`, as the elements in `num_list` are integers. If you want to print the data types of each element in `num_list` and `num_array`, you can modify the code as follows:

```python
# Print data types of each element in num_list
print("Data types in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

# Print data types of each element in num_array
print("\nData types in num_array:")
for sublist in num_array:
    for element in sublist:
        print(type(element))
```

This will print the data types of each individual element in both `num_list` and `num_array`.

**Q4. Write a code to find the following characteristics of variable, num_array:**<br>
(i) shape<br>
(ii) size<br>

The shape attribute gives you a tuple representing the dimensions of the array, and the size attribute gives you the total number of elements in the array.

Certainly! Here's a different example:

```python
import numpy as np

# Create a 2x3 array with random integers
random_array = np.random.randint(1, 10, size=(2, 3))

# (i) Find the shape of random_array
shape_of_random_array = random_array.shape

# (ii) Find the size of random_array
size_of_random_array = random_array.size

# Print the characteristics
print("Array:")
print(random_array)
print("Shape of random_array:", shape_of_random_array)
print("Size of random_array:", size_of_random_array)
```

In this example, I've created a 2x3 NumPy array (`random_array`) with random integers between 1 and 10. The code then prints the array, its shape, and its size. You can replace the creation of `random_array` with your own array data or use different shapes to explore various scenarios.

**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.**<br>
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Certainly! You can use the `np.zeros` function to create a 3x3 NumPy array containing zeros. Here's the code:

```python
import numpy as np

# Create a 3x3 array containing zeros
zero_array = np.zeros((3, 3))

# Print the array
print(zero_array)
```

In this code, `np.zeros((3, 3))` creates a 3x3 array filled with zeros. The shape of the array is specified as `(3, 3)`. The resulting `zero_array` will look like this:

```
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

**Q6. Create an identity matrix of shape (5,5) using numpy functions?**<br>
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Certainly! You can use the `np.diag` function to create a diagonal matrix with the specified diagonal elements. Here's the code:

```python
import numpy as np

# Create a 5x5 diagonal matrix with diagonal elements equal to 1
data1 = np.diag([1, 1, 1, 1, 1])

# Print the diagonal matrix
print(data1)
```

The resulting `data1` will look like this:

```
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
```

This is equivalent to the identity matrix, as all diagonal elements are 1, and the off-diagonal elements are 0.